version: '3.7'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: cdd
      POSTGRES_PASSWORD: cdd
      POSTGRES_DB: cdd
      POSTGRES_SCHEMA: cdd
    restart: always
