version: '3.7'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_SCHEMA: test
    restart: always
